### ISSUE TITLE
Allow multiple IfConditionVariable

### ISSUE THREAD

**Issue by Basile-z** [Basile-z/styx#4]
Example

```c
if (const auto a = call() && var auto b = otherCall())
{/*a and b are defined in this scope*/}
else
{/*a and b are not defined anymore*/}
```

Not applicable directly, a slight refactoring of the rules is needed.

**Comment by BBasile** [comment]
Proposed syntax **looks** actually slightly ambiguous. Maybe colon or semicolon could be used...
That being said, there would be just one lookup to do after logical operator, e.g

```d
if (current().isTokLogicalOperator() && lookupNext().isStorageClass())
    nextIsDeclaration = true;
```
